const GITHUB_AUTH_TOKEN = "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"
const BOT_NUMBER = "258858286090"
const SESSION_ID = "PRABATH-MD~gm92ADYb#8SjnHMfR_5NPE_MW1Wweo-3uBitCD2QQrGoxEX-aVUs"


module.exports = {
GITHUB_AUTH_TOKEN,
BOT_NUMBER,
SESSION_ID
}
